from typing import Protocol, List

from DTO.Category import Category
from DTO.Event import Event


class IEventRepository(Protocol):
    def add(self, event: Event) -> int: ...
    def update(self, event: Event) -> None: ...
    def delete(self, event_id: int) -> None: ...
    def get_all(self) -> List[Event]: ...
    def get_dirty_records(self) -> List[Event]: ...

class ICategoryRepository(Protocol):
    def add(self, category: Category) -> int: ...
    def update(self, category: Category) -> None: ...
    def delete(self, category_id: int) -> None: ...
    def get_all(self) -> List[Category]: ...

class ISyncMediator(Protocol):
    def run_two_way_sync(self) -> None: ...