from datetime import date
from typing import Protocol, List, Optional

from DTO.category_DTO import CategoryDTO
from DTO.event_DTO import EventDTO

class IEventQuery(Protocol):
    def overdue(self) -> 'IEventQuery': ...
    def high_priority(self) -> 'IEventQuery': ...
    def low_priority(self) -> 'IEventQuery': ...
    def by_category(self, category_id: int) -> 'IEventQuery': ...
    def for_date(self, target_date: date) -> 'IEventQuery': ...
    def sort_by(self, field_name: str, ascending: bool = True) -> 'IEventQuery': ...
    def get_list(self) -> List[EventDTO]: ...

class IEventRepository(Protocol):
    def add(self, event: EventDTO) -> int: ...
    def update(self, event: EventDTO) -> None: ...
    def delete(self, event_id: int) -> None: ...
    def get_all(self) -> List[EventDTO]: ...
    def get_dirty_records(self) -> List[EventDTO]: ...
    def get_by_id(self, event_id: int) -> Optional[EventDTO]: ...

    def query(self) -> 'IEventQuery': ...

class ICategoryRepository(Protocol):
    def add(self, category: CategoryDTO) -> int: ...
    def update(self, category: CategoryDTO) -> None: ...
    def delete(self, category_id: int) -> None: ...
    def get_all(self) -> List[CategoryDTO]: ...
    def get_by_id(self, category_id: int) -> Optional[CategoryDTO]: ...

class ISyncMediator(Protocol):
    def run_two_way_sync(self) -> None: ...